import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import TabSelector from "@/components/TabSelector/TabSelector";
import { useState } from "react";
import AddExpenseForm from "./AddExpenseForm";
import AddIncomeForm from "./AddIncomeForm";

const Add = () => {
  const options = [
    {
      label: "Add Expense",
      value: "Add Expense",
    },
    {
      label: "Add Income",
      value: "Add Income",
    },
  ];
  const [selectedTab, setSelectedTab] = useState(0);

  const onTabChange = (e: any) => {
    setSelectedTab(e.index);
  };
  return (
    <>
      <Head>
        <title>Add Expense</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles["add-expense-container"]}>
          <TabSelector
            options={options}
            activeIndex={selectedTab}
            onTabChange={onTabChange}
          />
          {selectedTab === 0 ? <AddExpenseForm /> : <AddIncomeForm />}
        </div>
      </main>
    </>
  );
};

export default Add;
